# Generated by Django 5.0.6 on 2024-07-16 17:12

import apps.rental_announcement.choices.type_of_object
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Cancelled', 'CANCELLED')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewiews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_land', models.CharField(choices=[('BADEN_WUERTTEMBERG', 'Baden-Württemberg'), ('BAYERN', 'Bayern'), ('BERLIN', 'Berlin'), ('BRANDENBURG', 'Brandenburg'), ('BREMEN', 'Bremen'), ('HAMBURG', 'Hamburg'), ('HESSEN', 'Hessen'), ('MECKLENBURG_VORPOMMERN', 'Mecklenburg-Vorpommern'), ('NIEDERSACHSEN', 'Niedersachsen'), ('NORDRHEIN_WESTFALEN', 'Nordrhein-Westfalen'), ('RHEINLAND_PFALZ', 'Rheinland-Pfalz'), ('SAARLAND', 'Saarland'), ('SACHSEN', 'Sachsen'), ('SACHSEN_ANHALT', 'Sachsen-Anhalt'), ('SCHLESWIG_HOLSTEIN', 'Schleswig-Holstein'), ('THUERINGEN', 'Thüringen')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=75)),
                ('house_number', models.CharField(max_length=5)),
                ('postal_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'unique_together': {('federal_land', 'city', 'street', 'house_number', 'postal_code')},
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.SmallIntegerField()),
                ('type_of_object', models.CharField(choices=apps.rental_announcement.choices.type_of_object.HousingTypes.choices, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='rental_announcement.address')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
