# Generated by Django 5.0.6 on 2024-07-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_announcement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type_of_object',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Room'), ('STUDIO', 'Studio'), ('LOFT', 'Loft'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('CONDO', 'Condo'), ('COTTAGE', 'Cottage'), ('VILLA', 'Villa'), ('PENTHOUSE', 'Penthouse'), ('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Cancelled', 'CANCELLED')], default='Pending', max_length=20),
        ),
    ]
