# Generated by Django 5.0.6 on 2024-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_announcement', '0003_booking_canceled_booking_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='federal_land',
            field=models.CharField(choices=[('Baden-Württemberg', 'Baden-Württemberg'), ('Bayern', 'Bayern'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Hamburg', 'Hamburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Niedersachsen', 'Niedersachsen'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Saarland', 'Saarland'), ('Sachsen', 'Sachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thüringen', 'Thüringen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type_of_object',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Room', 'Room'), ('Studio', 'Studio'), ('Loft', 'Loft'), ('Duplex', 'Duplex'), ('Townhouse', 'Townhouse'), ('Condo', 'Condo'), ('Cottage', 'Cottage'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse'), ('Hotel', 'Hotel'), ('Hostel', 'Hostel')], max_length=50),
        ),
    ]
