from apps.users.permissions.renter_permission import IsRenterOrReadOnly
from apps.users.permissions.lessor_permissions import IsOwnerOrReadOnly
from apps.users.permissions.object_owner_permission import IsOwner
